### ISSUE TITLE
How can i run Netflix cookies checker 

### ISSUE THREAD

**Issue by dattebayojos08** [RiyanPiro/Netflix-Cooker#1]
Can i use it on my Android using termux?

**Comment by RiyanPiro** [comment]
Your device must be rooted in order to use it.
If it is,
Install git: `pkg install git`
Clone the repo: `git clone https://github.com/RiyanPiro/Netflix-Cooker`

**Comment by RiyanPiro** [comment]
Your device must be rooted in order to use it.
If it is,
Install git: `pkg install git`
Clone the repo: `git clone https://github.com/RiyanPiro/Netflix-Cooker`
Navigate to project: `cd Netflix-Cooker`
Install requirements: `pip install -r requirements.txt`
Install tsu: `pkg install tsu`
Run the script: `sudo python main.py`
